import { ArrowRight, ArrowUpRight, Check, ClipboardList, HandCoins, HeartHandshake, MapPinned, PackageCheck, Sprout, Store, Wheat } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatRupees } from '../data/market.js';

export default function StoryPage() {
  return <div className="story-page">
    <header className="story-hero page-shell"><div className="breadcrumbs"><Link to="/">AgriLink</Link><span>/</span><span>The difference</span></div><p className="eyebrow"><Sprout size={15} /> AN OPEN MARKET BEGINS WITH AN OPEN CONVERSATION</p><h1>A shorter road<br />from <em>soil to table.</em></h1><p>The people who grow our food deserve more than a price at the end of the season. AgriLink puts a name, a harvest and an asking price in the same place.</p><Link className="button button-primary" to="/market">Look around the market <ArrowRight size={16} /></Link><div className="story-hero-aside"><span>THE NAME</span><b>First, a person.</b><i /> <span>THE PLACE</span><b>Then, a real place.</b><i /> <span>THE PRICE</span><b>Right out in the open.</b></div></header>
    <section className="three-steps-section page-shell" aria-labelledby="steps-heading"><p className="eyebrow">NOT A LONGER CHAIN. A SHORTER ONE.</p><h2 id="steps-heading">Three little things make <em>a difference.</em></h2><div className="three-steps-grid"><article><div className="step-number"><span>01</span><MapPinned size={20} /></div><h3>Know the ground.</h3><p>Each listing starts at its source: the farm or collective, a district and a grower's own account of the way they work.</p><span className="step-proof">ORIGIN, NOT AN IMPRESSION</span></article><article><div className="step-number"><span>02</span><PackageCheck size={20} /></div><h3>Follow the picking.</h3><p>Harvest timing, amount on hand and dispatch are shown as the farm shares them. New picking, new status—not marketing language dressed as a guarantee.</p><span className="step-proof">A GROWER'S FRESH NOTE</span></article><article><div className="step-number"><span>03</span><HandCoins size={20} /></div><h3>See the asking price.</h3><p>The grower's price stays beside their name. The demo's separate 4% example shows how a future service fee might be discussed, never hidden.</p><span className="step-proof">NO SILENT MIDDLEMEN</span></article></div></section>
    <section className="story-ledger-section"><div className="story-ledger-inner page-shell"><div><p className="eyebrow eyebrow-light">A NUMBER SHOULD NEVER HIDE THE PERSON</p><h2>All ₹100 of the<br /><em>story, accounted for.</em></h2><p>Before the market charges a real rupee, a grower and a buyer should be able to have this conversation first.</p><span className="story-ledger-sample"><Check size={15} /> Example only · no payments · no commissions processed</span></div><div className="ledger-illustration"><div className="ledger-top-row"><span>ILLUSTRATIVE HYPOTHESIS / NOT A LIVE RATE</span><span><ArrowUpRight size={15} /></span></div><div className="ledger-main-line"><span>Each ₹100 of asking price</span><b>₹100</b></div><div className="ledger-progress"><span /><i /></div><div className="ledger-label-row"><span><i className="ledger-key-farmer" /> Independent grower</span><strong>₹96</strong></div><div className="ledger-label-row"><span><i className="ledger-key-service" /> Future marketplace service</span><strong>₹4</strong></div><div className="ledger-rule" /><p className="ledger-footnote">If activated, an indicative 4% service charge could help support verification, listing tools and market access. Today, this is a product concept only.</p></div></div></section>
    <section className="model-section page-shell" aria-labelledby="model-heading"><div className="model-heading"><p className="eyebrow">A SENSIBLE WAY TO GROW, TOO</p><h2 id="model-heading">Start open. Grow on <em>your terms.</em></h2><p>Sample tiers are the business model a hackathon prototype could test—not plans currently on sale.</p></div><div className="tier-grid"><article className="tier-card"><span className="tier-kicker">THE OPEN STALL</span><h3>Start free.</h3><strong>{formatRupees(0)}<i> / month</i></strong><p>One grower. A handful of listings. A more direct way to meet the next buyer.</p><ul><li><Check size={15} /> Up to five active listings</li><li><Check size={15} /> Simple harvest and order notes</li><li><Check size={15} /> A profile shoppers can recognise</li></ul><span className="tier-example-note">Sample product direction. No real plan, limit or charge is activated here.</span></article><article className="tier-card tier-card-featured"><span className="tier-recommended"><Sprout size={12} />AN EXAMPLE TO DISCUSS</span><span className="tier-kicker">THE COLLECTIVE</span><h3>Grow together.</h3><strong>{formatRupees(399)}<i> / month · sample price</i></strong><p>A paid showcase for collectives reaching more buyers over a longer season.</p><ul><li><Check size={15} /> More sample grower listings</li><li><Check size={15} /> Group farm profiles</li><li><Check size={15} /> Shared seasonal-market analytics</li><li><Check size={15} /> Illustrative 2.5% order fee example</li></ul><span className="tier-example-note">Illustrative only. Subscriptions and transaction fees are disabled.</span></article></div><div className="model-note"><ClipboardList size={17} /><p><b>Prototype business assumptions:</b> for buyers, an indicative <b>4% per-order service charge</b> on the free tier; for an example <b>₹399/month Collective plan</b>, 2.5%. None of these rates has been validated, contracted or charged. Product and order figures are sample; order requests are not sales. <Link to="/market">See the open market <ArrowUpRight size={13} /></Link></p></div></section>
    <section className="story-final-cta page-shell"><div className="grower-cta-mark"><HeartHandshake size={25} /></div><div><p className="eyebrow">GOOD THINGS BEGIN BETWEEN PEOPLE</p><h2>Come a little closer.</h2><p>Have a look at the harvests, or bring something you've grown.</p></div><div className="story-cta-buttons"><Link className="button button-primary" to="/market">Find a harvest <ArrowRight size={16} /></Link><Link className="button button-paper-dark" to="/farmer"><Store size={15} /> Farm studio</Link></div></section>
    <footer className="mini-footer page-shell"><Link to="/">AgriLink</Link><span>Origin, pricing and review states belong to this demonstration—not regulated product certification.</span></footer>
  </div>;
}
